<?php 
    echo'
<footer>
    <section class="container-footer">
        <section class="quick-access">
          <h2>Quick Access</h2>
          <ul>
              <li><a href="index.php">Home</a></li>
              <li><a href="jobs.php">Job Description</a></li>
              <li><a href="apply.php">Apply Online</a></li>
              <li><a href="about.php">About Us</a></li>
              <li><a href="enhancements.php">Enhancements</a></li>
          </ul>
        </section>
        <section class="members">
          <h2>Members</h2>
          <ul>
              <li><a href="mailto:104700948@student.swin.edu.au">Tien</a></li>
              <li><a href="mailto:103980613@student.swin.edu.au ">Jean</a></li>
              <li><a href="mailto:105340099@student.swin.edu.au ">Mohamed</a></li>
            </ul>
        </section>
        <section class="more-info">
          <h2>For more information</h2>
          <a href="https://www.youtube.com/watch?v=XH4JbI0fUzw" class="footer-btn">Watch Video</a>
        </section>
        <section class="copyright-text">
          <p>Copyright &#169 2024. All Rights Reserved.</p>
          <p>Swinburne University of Technology</p>
        </section>
    </section>
</footer>';
?>